# -*- mode: org -*-
#+title: Running stuff and other related tasks
#+LANGUAGE:  en
#+AUTHOR: me
#+OPTIONS:   H:3 num:t   toc:3 \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   author:t creator:t timestamp:t email:t
#+DESCRIPTION: A description of things I would like to learn. The schedule contributes to calendar.
#+KEYWORDS:  org-mode Emacs organization GTD getting-things-done to-learn
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+CATEGORY: Running
#+TAGS: Running
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+TODO: TODO(t) WAIT(w@/!) | DONE(d!) CANCELED(c@)


* Important elements
[2024-03-12 Tue 21:47]
- cadence
- stride length/angle :: goal: land foot beneath a *flexing* knee, but don't overstride. As cadence increases, so should the stride angle. Stride angle: as one leg backward (maximum extension of leg backward) how high is the knee drive on the forward leg (angle between backward and forward leg when backward leg is extended the most)
- posture :: should run in a bending forward lean push, instead of just bending forward at the waist: focus on holding hips high, up, and forward: maintain an aligned posture from top to toe
- arm movements :: swing arms in relaxed and rhythmic coordination with stride, and motion should originate from shoulders

* Training
- fartlek
- strength

* Habit
  :PROPERTIES:
  :CATEGORY: Habit
  :LOGGING:  DONE(!)
  :ARCHIVE:  %s_archive::* Habits
  :END:

* Nutrition

